import type { NextApiRequest, NextApiResponse } from 'next';
import { verifyToken } from '@/lib/auth';
import { generateJadwalLuarGedungBOK } from '@/lib/randomizeLogic';
import { prisma } from '@/lib/prisma';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).end();
  if (!verifyToken(req, res)) return;

  const { bulan, tahun, preview } = req.body;
  if (!bulan || !tahun) return res.status(400).json({ error: 'bulan dan tahun diperlukan' });

  try {
    const { jadwal, skipped } = await generateJadwalLuarGedungBOK(parseInt(bulan), parseInt(tahun));

    if (preview) return res.json({ jadwal, skipped });

    const data = jadwal.map((j) => ({
      tanggal: new Date(j.tanggal),
      lokasi: j.lokasi,
      kegiatan: j.kegiatan,
      penyerta: j.penyerta,
      kategori: j.kategori,
      subKategori: j.sub_kategori ?? null,
      isAutoGenerated: true,
      source: 'randomize',
    }));
    const created = await prisma.kegiatan.createMany({ data });
    return res.json({ message: `${created.count} jadwal disimpan` });
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : 'Unknown error';
    return res.status(500).json({ error: msg });
  }
}